import { HelpCircle, ChevronDown } from 'lucide-react';
import { useState } from 'react';

const faqs = [
  { q: 'What is Cortex AI?', a: 'Cortex AI is a next-generation cryptocurrency trading platform that uses artificial intelligence and machine learning to generate trading signals, automate strategies, and provide real-time market sentiment analysis. Our Neural Engine v3 processes over 1,200 data sources to deliver actionable insights.' },
  { q: 'How do AI trading signals work?', a: 'Our AI signals are generated by analyzing on-chain data, social media sentiment, technical indicators, order book depth, and macroeconomic factors. Each signal includes an entry price, target, stop loss, and confidence score based on the AI\'s historical accuracy for similar setups.' },
  { q: 'Is my money safe with Cortex AI?', a: 'Cortex AI never holds your funds directly. We connect to your existing exchange accounts via API keys with read and trade permissions only — never withdrawal permissions. Your funds remain on your chosen exchange at all times.' },
  { q: 'What is the difference between Live and Paper trading?', a: 'Paper trading uses simulated funds to test strategies risk-free, perfect for learning and experimenting. Live trading executes real orders on connected exchanges with real capital. You can toggle between modes at any time from the top navigation bar.' },
  { q: 'How much capital do I need to start?', a: 'You can start paper trading with no capital at all. For live trading, the minimum recommended allocation is $100 or equivalent, though some strategies perform better with larger allocations. Always start with an amount you can afford to lose.' },
  { q: 'What strategies are available?', a: 'We offer three pre-built AI strategies — Aggressive Bull Scalper, AI Smart DCA, and Sideways Market Sniper — plus a custom bot builder where you can configure your own strategy core (Scalping, Grid, or Trailing), risk/reward parameters, and capital allocation.' },
  { q: 'Can I use leverage with Cortex AI?', a: 'Yes, when trading futures you can set leverage up to 100x. However, high leverage significantly increases liquidation risk. We recommend starting with lower leverage (5-10x) and only increasing it once you understand the risks involved.' },
  { q: 'Which exchanges are supported?', a: 'Currently we support Binance, Bybit, OKX, KuCoin, Coinbase Pro, and Kraken. New broker integrations are added regularly. Visit the "Connect Your Broker" page to link your exchange account.' },
  { q: 'What does the Panic Button do?', a: 'The Panic Button immediately market-sells all open positions and cancels all pending orders across all connected brokers. It is designed for emergency exits during sudden market crashes. This action is irreversible — use with caution.' },
  { q: 'How accurate are the AI predictions?', a: 'Our AI strategies maintain a 68-82% historical win rate depending on the strategy and market conditions. However, past performance does not guarantee future results. Crypto markets are highly volatile and losses are possible.' },
];

export default function FAQView() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <div className="space-y-5 animate-slide-up max-w-3xl">
      <div>
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <HelpCircle className="w-5 h-5 text-neon-cyan" />
          Frequently Asked Questions
        </h2>
        <p className="text-sm text-slate-400">Everything you need to know about Cortex AI</p>
      </div>

      <div className="space-y-2">
        {faqs.map((faq, i) => (
          <div key={i} className="glass-card overflow-hidden">
            <button
              onClick={() => setOpen(open === i ? null : i)}
              className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-white/[0.02] transition-colors"
            >
              <span className={`text-sm font-semibold ${open === i ? 'text-neon-cyan' : 'text-white'}`}>{faq.q}</span>
              <ChevronDown className={`w-4 h-4 flex-shrink-0 text-slate-400 transition-transform duration-300 ${open === i ? 'rotate-180 text-neon-cyan' : ''}`} />
            </button>
            <div className={`overflow-hidden transition-all duration-300 ${open === i ? 'max-h-96' : 'max-h-0'}`}>
              <p className="px-5 pb-4 text-sm text-slate-400 leading-relaxed">{faq.a}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
