import { Radio, TrendingUp, TrendingDown, Minus, Brain } from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { signals } from '@/data/mockData';

const typeConfig = {
  BUY: { color: 'text-neon-green', bg: 'bg-neon-green/15', border: 'border-neon-green/30', icon: TrendingUp },
  SELL: { color: 'text-neon-red', bg: 'bg-neon-red/15', border: 'border-neon-red/30', icon: TrendingDown },
  HOLD: { color: 'text-neon-amber', bg: 'bg-neon-amber/15', border: 'border-neon-amber/30', icon: Minus },
};

export default function SignalsView() {
  const { formatCurrency: _ } = useApp();

  return (
    <div className="space-y-5 animate-slide-up">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Radio className="w-5 h-5 text-neon-cyan" />
            AI Trading Signals
          </h2>
          <p className="text-sm text-slate-400">Real-time signals generated by Cortex Neural Engine</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-neon-green opacity-75" />
            <span className="relative inline-flex rounded-full h-2 w-2 bg-neon-green" />
          </span>
          <span className="text-xs text-neon-green font-semibold">LIVE</span>
        </div>
      </div>

      {/* Signal cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {signals.map((sig) => {
          const tc = typeConfig[sig.type];
          const Icon = tc.icon;
          return (
            <div key={sig.id} className={`glass-card p-5 hover:${tc.border} transition-all duration-300`}>
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-xl ${tc.bg} ${tc.border} border flex items-center justify-center`}>
                    <Icon className={`w-5 h-5 ${tc.color}`} />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="text-lg font-bold text-white">{sig.coin}</h3>
                      <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold ${tc.bg} ${tc.color}`}>{sig.type}</span>
                    </div>
                    <p className="text-[10px] text-slate-500">{sig.timeframe} · {sig.timestamp}</p>
                  </div>
                </div>
              </div>

              {/* Confidence bar */}
              <div className="mb-3">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-[10px] text-slate-500">AI Confidence</span>
                  <span className={`text-xs font-bold ${tc.color}`}>{sig.confidence}%</span>
                </div>
                <div className="h-1.5 rounded-full bg-base-700 overflow-hidden">
                  <div
                    className={`h-full rounded-full ${tc.bg.replace('/15', '')} transition-all duration-1000`}
                    style={{ width: `${sig.confidence}%`, background: tc.color === 'text-neon-green' ? '#00ff9d' : tc.color === 'text-neon-red' ? '#ff3b5c' : '#ffb020' }}
                  />
                </div>
              </div>

              {/* Price levels */}
              <div className="grid grid-cols-3 gap-2 text-center">
                <div className="py-2 rounded-lg bg-white/[0.03]">
                  <p className="text-[9px] text-slate-500 uppercase">Entry</p>
                  <p className="text-xs font-bold text-slate-200 font-mono">${sig.entry.toLocaleString()}</p>
                </div>
                <div className="py-2 rounded-lg bg-neon-green/5">
                  <p className="text-[9px] text-neon-green/70 uppercase">Target</p>
                  <p className="text-xs font-bold text-neon-green font-mono">${sig.target.toLocaleString()}</p>
                </div>
                <div className="py-2 rounded-lg bg-neon-red/5">
                  <p className="text-[9px] text-neon-red/70 uppercase">Stop</p>
                  <p className="text-xs font-bold text-neon-red font-mono">${sig.stopLoss.toLocaleString()}</p>
                </div>
              </div>

              {/* Source */}
              <div className="mt-3 flex items-center gap-1.5 text-[10px] text-slate-500">
                <Brain className="w-3 h-3 text-neon-cyan" />
                {sig.source}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
